# Generated by Django 3.1.6 on 2021-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210609_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('emailid', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Mytable',
        ),
    ]
