# Generated by Django 3.1.6 on 2021-06-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210610_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('emailid', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contactus',
        ),
        migrations.DeleteModel(
            name='Fbuser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userreg'),
        ),
    ]
