# Generated by Django 3.1.6 on 2021-07-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
    ]
