# Generated by Django 3.1.6 on 2021-07-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210701_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='datas',
        ),
    ]
