# Generated by Django 3.1.6 on 2021-07-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
