# Generated by Django 3.1.6 on 2021-07-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
