# Generated by Django 3.1.6 on 2021-07-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
