# Generated by Django 3.1.6 on 2021-07-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_contact_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='emailid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='lastname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='pas',
        ),
    ]
