# Generated by Django 3.1.6 on 2021-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210707_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uname',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
