# Generated by Django 3.1.6 on 2021-07-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_registration_uname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registration',
            new_name='reg',
        ),
    ]
