# Generated by Django 3.1.6 on 2021-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='uhj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cod', models.CharField(max_length=255)),
            ],
        ),
    ]
