# Generated by Django 3.1.6 on 2021-08-31 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='picat',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='home.blogcategory'),
        ),
    ]
