# Generated by Django 3.1.6 on 2021-08-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uhj',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
