# Generated by Django 3.1.6 on 2021-09-01 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Userprofile',
        ),
    ]
