# Generated by Django 3.1.6 on 2021-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20210901_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='about',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
