# Generated by Django 3.1.6 on 2021-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='propic',
            field=models.ImageField(blank=True, upload_to='propic'),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
