# Generated by Django 3.1.6 on 2021-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20211005_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='propic',
            field=models.ImageField(default='12mk.jpg', upload_to='propic'),
        ),
    ]
