# Generated by Django 3.1.6 on 2021-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20211005_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='12mk.jpg', upload_to='thumb'),
        ),
    ]
