# Generated by Django 3.1.6 on 2021-10-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20211005_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='alex.jpg', upload_to='thumb'),
        ),
    ]
